language: python

python:
  - "2.7"

addons:
  firefox: "41.0"
# command to install dependencies

install:
  - pip install --upgrade pip
  - pip install -r venv/requirements.txt
  - nodeenv -p --prebuilt --requirements=venv/npm-requirements.txt
  
# command to run tests
script: xvfb-run -a nosetests && cd tests && xvfb-run -a jasmine-ci && cd ../